### ISSUE TITLE
Cannot merge half-slider with theme

### ISSUE THREAD

**Issue by mymjack** [mymjack/CUAUT-new-website#4]
It seems that I can't merge the two css files together. I have heard that using multiple css files will increase loading time, especially for our web which is slow enough.

**Comment by ZiningZhu** [comment]
Don't worry they will merge automatically when loading. I guess cuaut.com is slow to open here because the server is in China. Various other ways can make it faster, including buying another site name (e.g: cuaut.ca)

**Comment by mymjack** [comment]
I am writing my own banner now.
